export const data = {
  data: {
    response_type: 'VEHICLE_DETAIL',
    scrape_request: null,
    scrapingInfo: null,
    refreshAllowed: null,
    viewType: 'COMPLETE',
    title: 'RC Details',
    keys: {
      groups: [
        {
          id: null,
          fields: [
            {
              key: 'Owner Name',
              value: 'DAWOOD AHMED ISMAIL',
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'REPORT',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Report',
                    textColor: '#000000',
                    bgColor: null,
                    color: null,
                    message: null,
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'MH01AT0696',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'DEFAULT',
            },
            {
              key: 'Ownership (Serial No)',
              value: 'First Owner',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Insurance Expired! 😱',
              value:
                'A lot of risks and penalties are involved if your policy lapses and it may require a re-inspection later. Click below to get best insurance quotes for your vehicle.',
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'BROWSER',
                    url: 'https://www.acko.com/lp/new-car-comprehensive/?utm_source=partnership&utm_medium=android_car-info&utm_campaign=carinfo&utm_term=details_screen_commercial&utm_content=card',
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'View Best Offer',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: null,
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: null,
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: 'BI_CAR_INSURANCE',
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'PROMINENT_NATIVE',
            },
          ],
          title: 'Ownership Details',
        },
        {
          id: null,
          fields: [
            {
              key: 'Maker Model',
              value: 'MARUTI SUZUKI INDIA LTD, MARUTI OMNI E MPI STD BSIV',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Vehicle Class',
              value: 'Motor Cab(LPV)',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Quick Actions',
              value: null,
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'CHECK_CHALLANS',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Check Challan',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message:
                      'Get pending violations and fines to avoid penalties',
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'MH01AT0696',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
                {
                  data: {
                    cta: 'CHECK_VALUE',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Check Price',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: 'Check resale market value of this vehicle',
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: {
                      category: {
                        key: '1',
                        value: 'Car',
                        name: 'Car',
                        resultAction: null,
                      },
                      brand: {
                        key: 'MARUTISUZUKI',
                        value: 'Maruti Suzuki',
                        name: 'Maruti Suzuki',
                        resultAction: null,
                      },
                      model: {
                        key: 'OMNI',
                        value: 'Omni',
                        name: 'Omni',
                        resultAction: null,
                      },
                      year: {
                        key: '2010',
                        value: '2010',
                        name: '2010',
                        resultAction: null,
                      },
                      trim: null,
                      km: {
                        key: '100000-120000',
                        value: '1 lac+ km',
                        name: '1 lac+ km',
                        resultAction: null,
                      },
                    },
                    leadType: null,
                    id: 'MH01AT0696',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'QUICK_ACTIONS',
            },
            {
              key: 'Fuel Type',
              value: 'PETROL/CNG',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Fuel norms',
              value: 'Not Available',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: null,
              value: null,
              icon: null,
              resultActions: null,
              cardType: 'SMART_AD',
            },
            {
              key: 'Engine no.',
              value: 'F8BIN-42XXXXX',
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'COPY',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Copy',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: null,
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'copy',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'DEFAULT',
            },
            {
              key: 'Chassis no.',
              value: 'MA3EVB-11S0-12XXXXX',
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'COPY',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Copy',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: null,
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'copy',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'DEFAULT',
            },
          ],
          title: 'Vehicle Details',
        },
        {
          id: null,
          fields: [
            {
              key: 'Registration date',
              value: '27-Aug-2010',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Vehicle Age',
              value: '11 years , 0 month &27 days ',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Quick Actions',
              value: null,
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'CHECK_CHALLANS',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Check Challan',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message:
                      'Get pending violations and fines to avoid penalties',
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'MH01AT0696',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
                {
                  data: {
                    cta: 'CHECK_VALUE',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Check Price',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: 'Check resale market value of this vehicle',
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: {
                      category: {
                        key: '1',
                        value: 'Car',
                        name: 'Car',
                        resultAction: null,
                      },
                      brand: {
                        key: 'MARUTISUZUKI',
                        value: 'Maruti Suzuki',
                        name: 'Maruti Suzuki',
                        resultAction: null,
                      },
                      model: {
                        key: 'OMNI',
                        value: 'Omni',
                        name: 'Omni',
                        resultAction: null,
                      },
                      year: {
                        key: '2010',
                        value: '2010',
                        name: '2010',
                        resultAction: null,
                      },
                      trim: null,
                      km: {
                        key: '100000-120000',
                        value: '1 lac+ km',
                        name: '1 lac+ km',
                        resultAction: null,
                      },
                    },
                    leadType: null,
                    id: 'MH01AT0696',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'QUICK_ACTIONS',
            },
            {
              key: 'Fitness upto',
              value: '21-Jun-2020',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Insurance expiry (tentative)',
              value: '11-Sep-2019',
              icon: null,
              resultActions: null,
              cardType: 'DYNAMIC_REMINDER',
            },
            {
              key: 'Insurance Expired! 😱',
              value:
                'A lot of risks and penalties are involved if your policy lapses and it may require a re-inspection later. Click below to get best insurance quotes for your vehicle.',
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'BROWSER',
                    url: 'https://www.acko.com/lp/new-car-comprehensive/?utm_source=partnership&utm_medium=android_car-info&utm_campaign=carinfo&utm_term=details_screen_commercial&utm_content=card',
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'View Best Offer',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: null,
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: null,
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: 'BI_CAR_INSURANCE',
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
              ],
              cardType: 'PROMINENT_NATIVE',
            },
          ],
          title: 'Important Dates',
        },
        {
          id: null,
          fields: [
            {
              key: 'Registration no.',
              value: 'MH01AT0696',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Color',
              value: 'BY',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Unloaded weight (Kg)',
              value: '785',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Engine capacity (cc)',
              value: '1086.00',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
          ],
          title: 'Additional Details',
        },
        {
          id: null,
          fields: [
            {
              key: null,
              value: null,
              icon: null,
              resultActions: null,
              cardType: 'SMART_AD',
            },
          ],
          title: null,
        },
        {
          id: null,
          fields: [
            {
              key: 'Name',
              value: 'MUMBAI (CENTRAL), Maharashtra',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Code',
              value: 'MH01',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'RTO Address',
              value: 'Old Bodyguard Lane Tulsewadi, Tardev, Mumbai Central',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'RTO Phone',
              value: '022-23532337',
              icon: null,
              resultActions: null,
              cardType: 'DEFAULT',
            },
            {
              key: 'Quick Actions',
              value: null,
              icon: null,
              resultActions: [
                {
                  data: {
                    cta: 'CAR_SPECS',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'See Specs',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: 'Check ex-showroom price, mileage & more',
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'CAR_SPECS',
                    modelId: '36',
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: 'BUTTON',
                },
                {
                  data: {
                    cta: 'SHARE',
                    url: null,
                    packageName: null,
                    phoneNo: null,
                    reminderText: null,
                    scraperInfo: null,
                    background: false,
                    timestamp: null,
                    dialogueText: null,
                    text: 'Share Result',
                    textColor: null,
                    bgColor: null,
                    color: null,
                    message: 'Share details of this vehicle with your friends',
                    messageColor: null,
                    client: null,
                    carDetails: null,
                    leadActions: null,
                    meta: null,
                    valuationData: null,
                    leadType: null,
                    id: 'SHARE',
                    modelId: null,
                    partnerId: null,
                    phone: null,
                    bottomSheet: null,
                    reminderType: null,
                    iconUrl: null,
                    desc: null,
                    partnerLogoImageURL: null,
                    accessoryImageURL: null,
                    borderColor: null,
                    eventId: null,
                    netcoreEvent: null,
                  },
                  type: null,
                },
              ],
              cardType: 'QUICK_ACTIONS',
            },
          ],
          title: 'RTO Details',
        },
        {
          id: null,
          fields: [
            {
              key: null,
              value:
                'Disclaimer: This mobile app is neither affiliated nor connected with any Government entity and provides details about vehicles that are already publicly available on Government Parivahan Service, without tampering or altering any information. This mobile app does not represent any Government entity. The contents of this app are purely for informational purposes. The users may verify the data made available on this mobile app from Government Parivahan Service.',
              icon: null,
              resultActions: null,
              cardType: 'INFO',
            },
          ],
          title: null,
        },
      ],
      title: null,
      msg: null,
      shareText:
        "Check registration details, pending challans, and resale value of vehicle no. MH01AT0696 owned by D*W*O* *H*E* *S*A*L on India's #1 RTO Vehicle Information app: CarInfo.",
      imageURL:
        'http://d1egxr9rlacnzd.cloudfront.net/unsafe/https://s3.ap-south-1.amazonaws.com/carinfo.cdn/cars/10/36/0/Omni.jpg',
      registrationNumber: 'MH01AT0696',
      createdAt: 1565526658984,
      ownerName: 'DAWOOD AHMED ISMAIL',
      homeActions: [
        {
          data: {
            cta: 'CHECK_CHALLANS',
            url: null,
            packageName: null,
            phoneNo: null,
            reminderText: null,
            scraperInfo: null,
            background: false,
            timestamp: null,
            dialogueText: null,
            text: 'Check Challan',
            textColor: '#FFFFFF',
            bgColor: null,
            color: '#444141',
            message: 'Check pending challans and pay online',
            messageColor: '#787878',
            client: null,
            carDetails: null,
            leadActions: null,
            meta: null,
            valuationData: null,
            leadType: null,
            id: 'MH01AT0696',
            modelId: null,
            partnerId: null,
            phone: null,
            bottomSheet: null,
            reminderType: null,
            iconUrl: null,
            desc: null,
            partnerLogoImageURL: null,
            accessoryImageURL: null,
            borderColor: null,
            eventId: null,
            netcoreEvent: null,
          },
          type: 'BUTTON',
        },
      ],
      topActions: {
        first: {
          key: 'Registation no.',
          value: 'MH01AT0696',
          icon: null,
          resultActions: null,
          cardType: 'DEFAULT',
        },
        second: {
          key: 'Insurance expiry',
          value: '11-Sep-2019',
          icon: null,
          resultActions: null,
          cardType: 'DEFAULT',
        },
        availableActions: [
          {
            key: 'Renew insurance',
            value: 'Insurance expired\n on11-Sep-2019',
            icon: null,
            resultActions: [
              {
                data: {
                  cta: 'BROWSER',
                  url: 'https://www.acko.com/lp/new-car-comprehensive/?utm_source=partnership&utm_medium=android_car-info&utm_campaign=carinfo&utm_term=details_screen_commercial&utm_content=top_actions',
                  packageName: null,
                  phoneNo: null,
                  reminderText: null,
                  scraperInfo: null,
                  background: false,
                  timestamp: null,
                  dialogueText: null,
                  text: 'View Best Offer',
                  textColor: null,
                  bgColor: null,
                  color: null,
                  message: null,
                  messageColor: null,
                  client: null,
                  carDetails: null,
                  leadActions: null,
                  meta: null,
                  valuationData: null,
                  leadType: null,
                  id: null,
                  modelId: null,
                  partnerId: null,
                  phone: null,
                  bottomSheet: null,
                  reminderType: null,
                  iconUrl: null,
                  desc: null,
                  partnerLogoImageURL: null,
                  accessoryImageURL: null,
                  borderColor: null,
                  eventId: 'BI_CAR_INSURANCE',
                  netcoreEvent: null,
                },
                type: 'BUTTON',
              },
            ],
            cardType: 'PROMINENT_NATIVE',
          },
          {
            key: 'Check price',
            value: 'Check resale market value',
            icon: null,
            resultActions: [
              {
                data: {
                  cta: 'CHECK_VALUE',
                  url: null,
                  packageName: null,
                  phoneNo: null,
                  reminderText: null,
                  scraperInfo: null,
                  background: false,
                  timestamp: null,
                  dialogueText: null,
                  text: null,
                  textColor: null,
                  bgColor: null,
                  color: null,
                  message: null,
                  messageColor: null,
                  client: null,
                  carDetails: null,
                  leadActions: null,
                  meta: null,
                  valuationData: null,
                  leadType: null,
                  id: 'MH01AT0696',
                  modelId: null,
                  partnerId: null,
                  phone: null,
                  bottomSheet: null,
                  reminderType: null,
                  iconUrl: null,
                  desc: null,
                  partnerLogoImageURL: null,
                  accessoryImageURL: null,
                  borderColor: null,
                  eventId: null,
                  netcoreEvent: null,
                },
                type: 'BUTTON',
              },
            ],
            cardType: 'DEFAULT',
          },
        ],
      },
      brandName: 'Omni',
      other: {
        textColor: '#FFFFFF',
        backgroundImage:
          'http://d1egxr9rlacnzd.cloudfront.net/unsafe/https://s3.ap-south-1.amazonaws.com/carinfo.cdn/October1st2019/bg_6.png',
        brandImage:
          'https://imgd.aeplcdn.com/0x0/cw/brands/logos/maruti.png?v=9',
        bgColor: '#444141',
        type: null,
        disableRatingPopup: false,
      },
      rcImageDto: {
        imageUrl:
          'http://d1egxr9rlacnzd.cloudfront.net/unsafe/https://s3.ap-south-1.amazonaws.com/carinfo.cdn/cars/10/36/0/Omni.jpg',
        modelId: '36',
        cta: 'CAR_SPECS',
        modelName: 'Omni',
      },
    },
    searchCount: null,
    popular: null,
  },
  errors: null,
};
